version: '3.9'

services:

  redis:
    image: redis:alpine

  api:
    build: ./api/
    container_name: api
    env_file:
      - .env
    restart: always
    ports: 
      - "8000:8000"
    depends_on:
      - webhook

  webhook:
    build: ./webhook/
    env_file:
      - .env
    depends_on:
      - redis